import normalize from 'react-native-normalize';
import {StatusBar, Platform, Dimensions} from 'react-native';

import color from '@styles/color';
import themeStyle from '@styles/theme.style';
import {hasHomeButton} from '@utils/DeviceInfo';

export const {width, height} = Dimensions.get('screen');
const statusBarHeight = StatusBar.currentHeight;

export const homeStyle: any = {
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: color.WHITE,
    marginTop: Platform.OS === 'android' ? statusBarHeight : 0,
  },
  txtTitle: {
    fontSize: 24,
    color: color.BLACK,
    marginVertical: normalize(10),
    marginBottom: normalize(10),
    fontFamily: themeStyle.FONT_BOLD,
  },
  itemNote: {
    alignSelf: 'center',
    height: normalize(120),
    width: width - normalize(16 * 2),
    borderRadius: normalize(16),
    marginBottom: normalize(16),
    padding: normalize(16),
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  containerNote: {
    flex: 1,
    backgroundColor: color.WHITE,
  },
  itemCurrency: {
    flexDirection: 'row',
    padding: normalize(16),
    paddingBottom: normalize(5),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  txtCurrency: {
    fontSize: 18,
    color: color.BLACK,
    marginLeft: normalize(16),
    fontFamily: themeStyle.FONT_FAMILY,
  },
  flag: {
    borderRadius: normalize(3),
  },
  txtTitleSheet: {
    fontSize: 18,
    fontFamily: themeStyle.FONT_BOLD,
    alignSelf: 'center',
  },
  txtSymbol: {
    color: 'gray',
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 18,
  },
  flex1: {
    flex: 1,
  },
  ScrollView: {
    flexGrow: 1,
  },
  itemColor: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: normalize(50),
    marginBottom: normalize(16),
    borderRadius: normalize(10),
    marginHorizontal: normalize(5),
  },
  listColor: {
    margin: normalize(16),
  },
  addNew: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(15),
    backgroundColor: '#EB5758',
    marginHorizontal: normalize(16),
    marginBottom:
      Platform.OS === 'android' || hasHomeButton() ? normalize(15) : 0,
    marginTop: normalize(16),
    height: normalize(45),
  },
  txtAdd: {
    fontSize: 20,
    alignSelf: 'center',
    color: color.WHITE,
    fontFamily: themeStyle.FONT_BOLD,
  },
  txtTitleMember: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_BOLD,
  },
  avatarFrame: {
    height: normalize(50),
    width: normalize(50),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999999999,
    marginVertical: normalize(10),
    backgroundColor: '#6763FD',
  },
  txtNameMember: {
    fontSize: 16,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  viewMembers: {
    marginRight: normalize(10),
    width: normalize(70),
    alignItems: 'center',
    height: normalize(110),
  },
  txtAvatar: {
    fontSize: 20,
    color: '#FFFFFF',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: themeStyle.FONT_BOLD,
  },
  deleteMember: {
    position: 'absolute',
    height: normalize(20),
    width: normalize(20),
    borderRadius: 999999999,
    backgroundColor: 'white',
    right: normalize(10),
    top: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  contentContainer: {
    flexGrow: 1,
  },
  headerInputMember: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: normalize(16),
    paddingBottom: normalize(10),
  },
  txtDone: {
    color: 'red',
    fontSize: 18,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  viewHeaderHome: {
    marginHorizontal: normalize(28),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  txtTitleNote: {
    fontSize: 18,
    fontFamily: themeStyle.FONT_BOLD,
  },
  txtTime: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_FAMILY,
    color: 'gray',
    marginTop: normalize(5),
  },
  headerItemNote: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  InfoNote: {
    flex: 1,
  },
  statusDot: {
    alignSelf: 'center',
    height: normalize(10),
    width: normalize(10),
    marginRight: normalize(6),
    borderRadius: normalize(28),
  },
  iconContainer: {
    height: normalize(120),
    width: normalize(150),
    position: 'absolute',
    right: normalize(16),
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: -9999,
    borderRadius: normalize(16),
    padding: normalize(16),
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderLeftWidth: normalize(0),
    // backgroundColor: 'red',
  },
  viewTotalContainer: {
    width: width - 32,
    // height: normalize(180),
    borderRadius: normalize(16),
    borderWidth: 1,
    alignSelf: 'center',
    padding:normalize(16),
    marginVertical: normalize(16),
  },
  viewTitleDetail: {
    paddingHorizontal: normalize(16),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: normalize(16),
    borderColor: color.SILVER,
    borderBottomWidth: 2,
  },
  txtTransaction: {
    fontSize: 18,
    fontFamily: themeStyle.FONT_BOLD,
  },
  txtViewAll: {
    fontSize: 16,
    color: color.DUSTY_GRAY,
    fontFamily: themeStyle.FONT_FAMILY,
  },
  viewAction: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginBottom: normalize(16),
  },
  noteAction: {
    alignItems: 'center',
  },
  txtNoteAction: {
    fontSize: 16,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: themeStyle.FONT_FAMILY,
  },
  iconNoteAction: {
    height: normalize(45),
    width: normalize(45),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: 'blue',
    marginBottom: normalize(8),
  },
  viewId: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: normalize(5),
  },
  txtId: {
    fontFamily: themeStyle.FONT_FAMILY,
    // color: color.WHITE,
    fontSize: 15,
    marginRight: normalize(5),
  },
  viewInfoNote: {
    // position: 'absolute',
    zIndex: 99999999999999,
    alignSelf: 'center',
    justifyContent: 'space-between',
    flex: 1,
    // backgroundColor:'blue',
    height: normalize(140),
    // top: 20,
  },
  viewEmpty: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: normalize(16),
  },
  txtEmptyTransactions: {
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 15,
    marginTop: normalize(8),
  },
  txtTotalSpending: {
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 20,
    // color: 'white',
    alignSelf: 'center',
  },
  txtTotalMoney: {
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 30,
    // color: 'white',
    marginRight: normalize(8),
  },
  viewTotalMoney: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    // marginVertical: normalize(16),
  },
  dashLine: {
    width: 250,
    hight: normalize(1),
    borderWidth: 0.5,
    alignSelf: 'center',
    borderColor: 'black',
  },
  txtAddExpense: {
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 18,
    marginTop: normalize(8),
    marginLeft: normalize(16),
  },
  imageOptions: {
    flex: 1,
    backgroundColor: 'white',
  },
  itemImageOptions: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: normalize(40),
    marginTop: normalize(15),
  },
  txtImageOptions: {
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 16,
    marginLeft: normalize(15),
  },
  notificationItemContainer: {
    flexDirection: 'row',
    padding: normalize(12),
    borderBottomWidth: 0.75,
    borderColor: 'gray',
  },
  notificationIcon: {
    height: normalize(30),
    width: normalize(30),
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: normalize(12),
    borderRadius: normalize(16),
  },
  notificationTitle: {
    fontSize: 15,
    fontFamily: themeStyle.FONT_BOLD,
  },
  notificationMessage: {
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 14,
    color: '#000',
    marginVertical: normalize(5),
  },
  notificationTime: {
    fontFamily: themeStyle.FONT_FAMILY,
    color: 'gray',
    fontSize: 12,
  },
  txtSearchMember: {
    paddingVertical: normalize(3),
    marginLeft: normalize(30),
    fontFamily: themeStyle.FONT_FAMILY,
    fontSize: 18,
  },
  dashLineNote: {
    height: normalize(1),
    width: '100%',
    backgroundColor: '#D1D5DB',
    borderColor: '#D1D5DB',
    alignSelf: 'center',
    borderRadius: normalize(30),
    marginVertical: normalize(12),
  },
  footerItemNote: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewTextName: {
    width: 30,
    height: 30,
    borderRadius: 25,
    alignItems: 'center',
    backgroundColor: 'red',
    justifyContent: 'center',
  },
  textName: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: themeStyle.FONT_BOLD,
  },
  viewHistory: {
    borderWidth: 2,
    paddingTop: normalize(16),
    marginHorizontal: normalize(16),
    borderRadius: normalize(8),
    borderColor: color.SILVER,
  },
  itemResultUser: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: normalize(8),
    marginHorizontal: normalize(16),
  },
  imageResultUser: {
    height: normalize(30),
    width: normalize(30),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999999999,
    backgroundColor: '#FFF5F5',
  },
  txtResultUser: {
    fontSize: 16,
    flex: 1,
    alignSelf: 'center',
    marginLeft: normalize(16),
    fontFamily: themeStyle.FONT_FAMILY,
  },
};
